package torch.scalapy.readwrite

trait FunctionWriters {
  implicit def function0Writer[O](implicit oWriter: _root_.me.shadaj.scalapy.readwrite.Writer[O]): _root_.me.shadaj.scalapy.readwrite.Writer[() => O] = ???

  implicit def function1Writer[T1, O](implicit r1: _root_.me.shadaj.scalapy.readwrite.Reader[T1], oWriter: _root_.me.shadaj.scalapy.readwrite.Writer[O]): _root_.me.shadaj.scalapy.readwrite.Writer[T1 => O] = ???

  implicit def function2Writer[T1, T2, O](implicit r1: _root_.me.shadaj.scalapy.readwrite.Reader[T1], r2: _root_.me.shadaj.scalapy.readwrite.Reader[T2], oWriter: _root_.me.shadaj.scalapy.readwrite.Writer[O]): _root_.me.shadaj.scalapy.readwrite.Writer[(T1, T2) => O] = ???

  implicit def function3Writer[T1, T2, T3, O](implicit r1: _root_.me.shadaj.scalapy.readwrite.Reader[T1], r2: _root_.me.shadaj.scalapy.readwrite.Reader[T2], r3: _root_.me.shadaj.scalapy.readwrite.Reader[T3], oWriter: _root_.me.shadaj.scalapy.readwrite.Writer[O]): _root_.me.shadaj.scalapy.readwrite.Writer[(T1, T2, T3) => O] = ???

  implicit def function4Writer[T1, T2, T3, T4, O](implicit r1: _root_.me.shadaj.scalapy.readwrite.Reader[T1], r2: _root_.me.shadaj.scalapy.readwrite.Reader[T2], r3: _root_.me.shadaj.scalapy.readwrite.Reader[T3], r4: _root_.me.shadaj.scalapy.readwrite.Reader[T4], oWriter: _root_.me.shadaj.scalapy.readwrite.Writer[O]): _root_.me.shadaj.scalapy.readwrite.Writer[(T1, T2, T3, T4) => O] = ???

  implicit def function5Writer[T1, T2, T3, T4, T5, O](implicit r1: _root_.me.shadaj.scalapy.readwrite.Reader[T1], r2: _root_.me.shadaj.scalapy.readwrite.Reader[T2], r3: _root_.me.shadaj.scalapy.readwrite.Reader[T3], r4: _root_.me.shadaj.scalapy.readwrite.Reader[T4], r5: _root_.me.shadaj.scalapy.readwrite.Reader[T5], oWriter: _root_.me.shadaj.scalapy.readwrite.Writer[O]): _root_.me.shadaj.scalapy.readwrite.Writer[(T1, T2, T3, T4, T5) => O] = ???

  implicit def function6Writer[T1, T2, T3, T4, T5, T6, O](implicit r1: _root_.me.shadaj.scalapy.readwrite.Reader[T1], r2: _root_.me.shadaj.scalapy.readwrite.Reader[T2], r3: _root_.me.shadaj.scalapy.readwrite.Reader[T3], r4: _root_.me.shadaj.scalapy.readwrite.Reader[T4], r5: _root_.me.shadaj.scalapy.readwrite.Reader[T5], r6: _root_.me.shadaj.scalapy.readwrite.Reader[T6], oWriter: _root_.me.shadaj.scalapy.readwrite.Writer[O]): _root_.me.shadaj.scalapy.readwrite.Writer[(T1, T2, T3, T4, T5, T6) => O] = ???

  implicit def function7Writer[T1, T2, T3, T4, T5, T6, T7, O](implicit r1: _root_.me.shadaj.scalapy.readwrite.Reader[T1], r2: _root_.me.shadaj.scalapy.readwrite.Reader[T2], r3: _root_.me.shadaj.scalapy.readwrite.Reader[T3], r4: _root_.me.shadaj.scalapy.readwrite.Reader[T4], r5: _root_.me.shadaj.scalapy.readwrite.Reader[T5], r6: _root_.me.shadaj.scalapy.readwrite.Reader[T6], r7: _root_.me.shadaj.scalapy.readwrite.Reader[T7], oWriter: _root_.me.shadaj.scalapy.readwrite.Writer[O]): _root_.me.shadaj.scalapy.readwrite.Writer[(T1, T2, T3, T4, T5, T6, T7) => O] = ???

  implicit def function8Writer[T1, T2, T3, T4, T5, T6, T7, T8, O](implicit r1: _root_.me.shadaj.scalapy.readwrite.Reader[T1], r2: _root_.me.shadaj.scalapy.readwrite.Reader[T2], r3: _root_.me.shadaj.scalapy.readwrite.Reader[T3], r4: _root_.me.shadaj.scalapy.readwrite.Reader[T4], r5: _root_.me.shadaj.scalapy.readwrite.Reader[T5], r6: _root_.me.shadaj.scalapy.readwrite.Reader[T6], r7: _root_.me.shadaj.scalapy.readwrite.Reader[T7], r8: _root_.me.shadaj.scalapy.readwrite.Reader[T8], oWriter: _root_.me.shadaj.scalapy.readwrite.Writer[O]): _root_.me.shadaj.scalapy.readwrite.Writer[(T1, T2, T3, T4, T5, T6, T7, T8) => O] = ???

  implicit def function9Writer[T1, T2, T3, T4, T5, T6, T7, T8, T9, O](implicit r1: _root_.me.shadaj.scalapy.readwrite.Reader[T1], r2: _root_.me.shadaj.scalapy.readwrite.Reader[T2], r3: _root_.me.shadaj.scalapy.readwrite.Reader[T3], r4: _root_.me.shadaj.scalapy.readwrite.Reader[T4], r5: _root_.me.shadaj.scalapy.readwrite.Reader[T5], r6: _root_.me.shadaj.scalapy.readwrite.Reader[T6], r7: _root_.me.shadaj.scalapy.readwrite.Reader[T7], r8: _root_.me.shadaj.scalapy.readwrite.Reader[T8], r9: _root_.me.shadaj.scalapy.readwrite.Reader[T9], oWriter: _root_.me.shadaj.scalapy.readwrite.Writer[O]): _root_.me.shadaj.scalapy.readwrite.Writer[(T1, T2, T3, T4, T5, T6, T7, T8, T9) => O] = ???

  implicit def function10Writer[T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, O](implicit r1: _root_.me.shadaj.scalapy.readwrite.Reader[T1], r2: _root_.me.shadaj.scalapy.readwrite.Reader[T2], r3: _root_.me.shadaj.scalapy.readwrite.Reader[T3], r4: _root_.me.shadaj.scalapy.readwrite.Reader[T4], r5: _root_.me.shadaj.scalapy.readwrite.Reader[T5], r6: _root_.me.shadaj.scalapy.readwrite.Reader[T6], r7: _root_.me.shadaj.scalapy.readwrite.Reader[T7], r8: _root_.me.shadaj.scalapy.readwrite.Reader[T8], r9: _root_.me.shadaj.scalapy.readwrite.Reader[T9], r10: _root_.me.shadaj.scalapy.readwrite.Reader[T10], oWriter: _root_.me.shadaj.scalapy.readwrite.Writer[O]): _root_.me.shadaj.scalapy.readwrite.Writer[(T1, T2, T3, T4, T5, T6, T7, T8, T9, T10) => O] = ???

  implicit def function11Writer[T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, T11, O](implicit r1: _root_.me.shadaj.scalapy.readwrite.Reader[T1], r2: _root_.me.shadaj.scalapy.readwrite.Reader[T2], r3: _root_.me.shadaj.scalapy.readwrite.Reader[T3], r4: _root_.me.shadaj.scalapy.readwrite.Reader[T4], r5: _root_.me.shadaj.scalapy.readwrite.Reader[T5], r6: _root_.me.shadaj.scalapy.readwrite.Reader[T6], r7: _root_.me.shadaj.scalapy.readwrite.Reader[T7], r8: _root_.me.shadaj.scalapy.readwrite.Reader[T8], r9: _root_.me.shadaj.scalapy.readwrite.Reader[T9], r10: _root_.me.shadaj.scalapy.readwrite.Reader[T10], r11: _root_.me.shadaj.scalapy.readwrite.Reader[T11], oWriter: _root_.me.shadaj.scalapy.readwrite.Writer[O]): _root_.me.shadaj.scalapy.readwrite.Writer[(T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, T11) => O] = ???

  implicit def function12Writer[T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, T11, T12, O](implicit r1: _root_.me.shadaj.scalapy.readwrite.Reader[T1], r2: _root_.me.shadaj.scalapy.readwrite.Reader[T2], r3: _root_.me.shadaj.scalapy.readwrite.Reader[T3], r4: _root_.me.shadaj.scalapy.readwrite.Reader[T4], r5: _root_.me.shadaj.scalapy.readwrite.Reader[T5], r6: _root_.me.shadaj.scalapy.readwrite.Reader[T6], r7: _root_.me.shadaj.scalapy.readwrite.Reader[T7], r8: _root_.me.shadaj.scalapy.readwrite.Reader[T8], r9: _root_.me.shadaj.scalapy.readwrite.Reader[T9], r10: _root_.me.shadaj.scalapy.readwrite.Reader[T10], r11: _root_.me.shadaj.scalapy.readwrite.Reader[T11], r12: _root_.me.shadaj.scalapy.readwrite.Reader[T12], oWriter: _root_.me.shadaj.scalapy.readwrite.Writer[O]): _root_.me.shadaj.scalapy.readwrite.Writer[(T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, T11, T12) => O] = ???

  implicit def function13Writer[T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, T11, T12, T13, O](implicit r1: _root_.me.shadaj.scalapy.readwrite.Reader[T1], r2: _root_.me.shadaj.scalapy.readwrite.Reader[T2], r3: _root_.me.shadaj.scalapy.readwrite.Reader[T3], r4: _root_.me.shadaj.scalapy.readwrite.Reader[T4], r5: _root_.me.shadaj.scalapy.readwrite.Reader[T5], r6: _root_.me.shadaj.scalapy.readwrite.Reader[T6], r7: _root_.me.shadaj.scalapy.readwrite.Reader[T7], r8: _root_.me.shadaj.scalapy.readwrite.Reader[T8], r9: _root_.me.shadaj.scalapy.readwrite.Reader[T9], r10: _root_.me.shadaj.scalapy.readwrite.Reader[T10], r11: _root_.me.shadaj.scalapy.readwrite.Reader[T11], r12: _root_.me.shadaj.scalapy.readwrite.Reader[T12], r13: _root_.me.shadaj.scalapy.readwrite.Reader[T13], oWriter: _root_.me.shadaj.scalapy.readwrite.Writer[O]): _root_.me.shadaj.scalapy.readwrite.Writer[(T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, T11, T12, T13) => O] = ???

  implicit def function14Writer[T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, T11, T12, T13, T14, O](implicit r1: _root_.me.shadaj.scalapy.readwrite.Reader[T1], r2: _root_.me.shadaj.scalapy.readwrite.Reader[T2], r3: _root_.me.shadaj.scalapy.readwrite.Reader[T3], r4: _root_.me.shadaj.scalapy.readwrite.Reader[T4], r5: _root_.me.shadaj.scalapy.readwrite.Reader[T5], r6: _root_.me.shadaj.scalapy.readwrite.Reader[T6], r7: _root_.me.shadaj.scalapy.readwrite.Reader[T7], r8: _root_.me.shadaj.scalapy.readwrite.Reader[T8], r9: _root_.me.shadaj.scalapy.readwrite.Reader[T9], r10: _root_.me.shadaj.scalapy.readwrite.Reader[T10], r11: _root_.me.shadaj.scalapy.readwrite.Reader[T11], r12: _root_.me.shadaj.scalapy.readwrite.Reader[T12], r13: _root_.me.shadaj.scalapy.readwrite.Reader[T13], r14: _root_.me.shadaj.scalapy.readwrite.Reader[T14], oWriter: _root_.me.shadaj.scalapy.readwrite.Writer[O]): _root_.me.shadaj.scalapy.readwrite.Writer[(T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, T11, T12, T13, T14) => O] = ???

  implicit def function15Writer[T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, T11, T12, T13, T14, T15, O](implicit r1: _root_.me.shadaj.scalapy.readwrite.Reader[T1], r2: _root_.me.shadaj.scalapy.readwrite.Reader[T2], r3: _root_.me.shadaj.scalapy.readwrite.Reader[T3], r4: _root_.me.shadaj.scalapy.readwrite.Reader[T4], r5: _root_.me.shadaj.scalapy.readwrite.Reader[T5], r6: _root_.me.shadaj.scalapy.readwrite.Reader[T6], r7: _root_.me.shadaj.scalapy.readwrite.Reader[T7], r8: _root_.me.shadaj.scalapy.readwrite.Reader[T8], r9: _root_.me.shadaj.scalapy.readwrite.Reader[T9], r10: _root_.me.shadaj.scalapy.readwrite.Reader[T10], r11: _root_.me.shadaj.scalapy.readwrite.Reader[T11], r12: _root_.me.shadaj.scalapy.readwrite.Reader[T12], r13: _root_.me.shadaj.scalapy.readwrite.Reader[T13], r14: _root_.me.shadaj.scalapy.readwrite.Reader[T14], r15: _root_.me.shadaj.scalapy.readwrite.Reader[T15], oWriter: _root_.me.shadaj.scalapy.readwrite.Writer[O]): _root_.me.shadaj.scalapy.readwrite.Writer[(T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, T11, T12, T13, T14, T15) => O] = ???

  implicit def function16Writer[T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, T11, T12, T13, T14, T15, T16, O](implicit r1: _root_.me.shadaj.scalapy.readwrite.Reader[T1], r2: _root_.me.shadaj.scalapy.readwrite.Reader[T2], r3: _root_.me.shadaj.scalapy.readwrite.Reader[T3], r4: _root_.me.shadaj.scalapy.readwrite.Reader[T4], r5: _root_.me.shadaj.scalapy.readwrite.Reader[T5], r6: _root_.me.shadaj.scalapy.readwrite.Reader[T6], r7: _root_.me.shadaj.scalapy.readwrite.Reader[T7], r8: _root_.me.shadaj.scalapy.readwrite.Reader[T8], r9: _root_.me.shadaj.scalapy.readwrite.Reader[T9], r10: _root_.me.shadaj.scalapy.readwrite.Reader[T10], r11: _root_.me.shadaj.scalapy.readwrite.Reader[T11], r12: _root_.me.shadaj.scalapy.readwrite.Reader[T12], r13: _root_.me.shadaj.scalapy.readwrite.Reader[T13], r14: _root_.me.shadaj.scalapy.readwrite.Reader[T14], r15: _root_.me.shadaj.scalapy.readwrite.Reader[T15], r16: _root_.me.shadaj.scalapy.readwrite.Reader[T16], oWriter: _root_.me.shadaj.scalapy.readwrite.Writer[O]): _root_.me.shadaj.scalapy.readwrite.Writer[(T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, T11, T12, T13, T14, T15, T16) => O] = ???

  implicit def function17Writer[T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, T11, T12, T13, T14, T15, T16, T17, O](implicit r1: _root_.me.shadaj.scalapy.readwrite.Reader[T1], r2: _root_.me.shadaj.scalapy.readwrite.Reader[T2], r3: _root_.me.shadaj.scalapy.readwrite.Reader[T3], r4: _root_.me.shadaj.scalapy.readwrite.Reader[T4], r5: _root_.me.shadaj.scalapy.readwrite.Reader[T5], r6: _root_.me.shadaj.scalapy.readwrite.Reader[T6], r7: _root_.me.shadaj.scalapy.readwrite.Reader[T7], r8: _root_.me.shadaj.scalapy.readwrite.Reader[T8], r9: _root_.me.shadaj.scalapy.readwrite.Reader[T9], r10: _root_.me.shadaj.scalapy.readwrite.Reader[T10], r11: _root_.me.shadaj.scalapy.readwrite.Reader[T11], r12: _root_.me.shadaj.scalapy.readwrite.Reader[T12], r13: _root_.me.shadaj.scalapy.readwrite.Reader[T13], r14: _root_.me.shadaj.scalapy.readwrite.Reader[T14], r15: _root_.me.shadaj.scalapy.readwrite.Reader[T15], r16: _root_.me.shadaj.scalapy.readwrite.Reader[T16], r17: _root_.me.shadaj.scalapy.readwrite.Reader[T17], oWriter: _root_.me.shadaj.scalapy.readwrite.Writer[O]): _root_.me.shadaj.scalapy.readwrite.Writer[(T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, T11, T12, T13, T14, T15, T16, T17) => O] = ???

  implicit def function18Writer[T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, T11, T12, T13, T14, T15, T16, T17, T18, O](implicit r1: _root_.me.shadaj.scalapy.readwrite.Reader[T1], r2: _root_.me.shadaj.scalapy.readwrite.Reader[T2], r3: _root_.me.shadaj.scalapy.readwrite.Reader[T3], r4: _root_.me.shadaj.scalapy.readwrite.Reader[T4], r5: _root_.me.shadaj.scalapy.readwrite.Reader[T5], r6: _root_.me.shadaj.scalapy.readwrite.Reader[T6], r7: _root_.me.shadaj.scalapy.readwrite.Reader[T7], r8: _root_.me.shadaj.scalapy.readwrite.Reader[T8], r9: _root_.me.shadaj.scalapy.readwrite.Reader[T9], r10: _root_.me.shadaj.scalapy.readwrite.Reader[T10], r11: _root_.me.shadaj.scalapy.readwrite.Reader[T11], r12: _root_.me.shadaj.scalapy.readwrite.Reader[T12], r13: _root_.me.shadaj.scalapy.readwrite.Reader[T13], r14: _root_.me.shadaj.scalapy.readwrite.Reader[T14], r15: _root_.me.shadaj.scalapy.readwrite.Reader[T15], r16: _root_.me.shadaj.scalapy.readwrite.Reader[T16], r17: _root_.me.shadaj.scalapy.readwrite.Reader[T17], r18: _root_.me.shadaj.scalapy.readwrite.Reader[T18], oWriter: _root_.me.shadaj.scalapy.readwrite.Writer[O]): _root_.me.shadaj.scalapy.readwrite.Writer[(T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, T11, T12, T13, T14, T15, T16, T17, T18) => O] = ???

  implicit def function19Writer[T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, T11, T12, T13, T14, T15, T16, T17, T18, T19, O](implicit r1: _root_.me.shadaj.scalapy.readwrite.Reader[T1], r2: _root_.me.shadaj.scalapy.readwrite.Reader[T2], r3: _root_.me.shadaj.scalapy.readwrite.Reader[T3], r4: _root_.me.shadaj.scalapy.readwrite.Reader[T4], r5: _root_.me.shadaj.scalapy.readwrite.Reader[T5], r6: _root_.me.shadaj.scalapy.readwrite.Reader[T6], r7: _root_.me.shadaj.scalapy.readwrite.Reader[T7], r8: _root_.me.shadaj.scalapy.readwrite.Reader[T8], r9: _root_.me.shadaj.scalapy.readwrite.Reader[T9], r10: _root_.me.shadaj.scalapy.readwrite.Reader[T10], r11: _root_.me.shadaj.scalapy.readwrite.Reader[T11], r12: _root_.me.shadaj.scalapy.readwrite.Reader[T12], r13: _root_.me.shadaj.scalapy.readwrite.Reader[T13], r14: _root_.me.shadaj.scalapy.readwrite.Reader[T14], r15: _root_.me.shadaj.scalapy.readwrite.Reader[T15], r16: _root_.me.shadaj.scalapy.readwrite.Reader[T16], r17: _root_.me.shadaj.scalapy.readwrite.Reader[T17], r18: _root_.me.shadaj.scalapy.readwrite.Reader[T18], r19: _root_.me.shadaj.scalapy.readwrite.Reader[T19], oWriter: _root_.me.shadaj.scalapy.readwrite.Writer[O]): _root_.me.shadaj.scalapy.readwrite.Writer[(T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, T11, T12, T13, T14, T15, T16, T17, T18, T19) => O] = ???

  implicit def function20Writer[T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, T11, T12, T13, T14, T15, T16, T17, T18, T19, T20, O](implicit r1: _root_.me.shadaj.scalapy.readwrite.Reader[T1], r2: _root_.me.shadaj.scalapy.readwrite.Reader[T2], r3: _root_.me.shadaj.scalapy.readwrite.Reader[T3], r4: _root_.me.shadaj.scalapy.readwrite.Reader[T4], r5: _root_.me.shadaj.scalapy.readwrite.Reader[T5], r6: _root_.me.shadaj.scalapy.readwrite.Reader[T6], r7: _root_.me.shadaj.scalapy.readwrite.Reader[T7], r8: _root_.me.shadaj.scalapy.readwrite.Reader[T8], r9: _root_.me.shadaj.scalapy.readwrite.Reader[T9], r10: _root_.me.shadaj.scalapy.readwrite.Reader[T10], r11: _root_.me.shadaj.scalapy.readwrite.Reader[T11], r12: _root_.me.shadaj.scalapy.readwrite.Reader[T12], r13: _root_.me.shadaj.scalapy.readwrite.Reader[T13], r14: _root_.me.shadaj.scalapy.readwrite.Reader[T14], r15: _root_.me.shadaj.scalapy.readwrite.Reader[T15], r16: _root_.me.shadaj.scalapy.readwrite.Reader[T16], r17: _root_.me.shadaj.scalapy.readwrite.Reader[T17], r18: _root_.me.shadaj.scalapy.readwrite.Reader[T18], r19: _root_.me.shadaj.scalapy.readwrite.Reader[T19], r20: _root_.me.shadaj.scalapy.readwrite.Reader[T20], oWriter: _root_.me.shadaj.scalapy.readwrite.Writer[O]): _root_.me.shadaj.scalapy.readwrite.Writer[(T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, T11, T12, T13, T14, T15, T16, T17, T18, T19, T20) => O] = ???

  implicit def function21Writer[T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, T11, T12, T13, T14, T15, T16, T17, T18, T19, T20, T21, O](implicit r1: _root_.me.shadaj.scalapy.readwrite.Reader[T1], r2: _root_.me.shadaj.scalapy.readwrite.Reader[T2], r3: _root_.me.shadaj.scalapy.readwrite.Reader[T3], r4: _root_.me.shadaj.scalapy.readwrite.Reader[T4], r5: _root_.me.shadaj.scalapy.readwrite.Reader[T5], r6: _root_.me.shadaj.scalapy.readwrite.Reader[T6], r7: _root_.me.shadaj.scalapy.readwrite.Reader[T7], r8: _root_.me.shadaj.scalapy.readwrite.Reader[T8], r9: _root_.me.shadaj.scalapy.readwrite.Reader[T9], r10: _root_.me.shadaj.scalapy.readwrite.Reader[T10], r11: _root_.me.shadaj.scalapy.readwrite.Reader[T11], r12: _root_.me.shadaj.scalapy.readwrite.Reader[T12], r13: _root_.me.shadaj.scalapy.readwrite.Reader[T13], r14: _root_.me.shadaj.scalapy.readwrite.Reader[T14], r15: _root_.me.shadaj.scalapy.readwrite.Reader[T15], r16: _root_.me.shadaj.scalapy.readwrite.Reader[T16], r17: _root_.me.shadaj.scalapy.readwrite.Reader[T17], r18: _root_.me.shadaj.scalapy.readwrite.Reader[T18], r19: _root_.me.shadaj.scalapy.readwrite.Reader[T19], r20: _root_.me.shadaj.scalapy.readwrite.Reader[T20], r21: _root_.me.shadaj.scalapy.readwrite.Reader[T21], oWriter: _root_.me.shadaj.scalapy.readwrite.Writer[O]): _root_.me.shadaj.scalapy.readwrite.Writer[(T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, T11, T12, T13, T14, T15, T16, T17, T18, T19, T20, T21) => O] = ???

  implicit def function22Writer[T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, T11, T12, T13, T14, T15, T16, T17, T18, T19, T20, T21, T22, O](implicit r1: _root_.me.shadaj.scalapy.readwrite.Reader[T1], r2: _root_.me.shadaj.scalapy.readwrite.Reader[T2], r3: _root_.me.shadaj.scalapy.readwrite.Reader[T3], r4: _root_.me.shadaj.scalapy.readwrite.Reader[T4], r5: _root_.me.shadaj.scalapy.readwrite.Reader[T5], r6: _root_.me.shadaj.scalapy.readwrite.Reader[T6], r7: _root_.me.shadaj.scalapy.readwrite.Reader[T7], r8: _root_.me.shadaj.scalapy.readwrite.Reader[T8], r9: _root_.me.shadaj.scalapy.readwrite.Reader[T9], r10: _root_.me.shadaj.scalapy.readwrite.Reader[T10], r11: _root_.me.shadaj.scalapy.readwrite.Reader[T11], r12: _root_.me.shadaj.scalapy.readwrite.Reader[T12], r13: _root_.me.shadaj.scalapy.readwrite.Reader[T13], r14: _root_.me.shadaj.scalapy.readwrite.Reader[T14], r15: _root_.me.shadaj.scalapy.readwrite.Reader[T15], r16: _root_.me.shadaj.scalapy.readwrite.Reader[T16], r17: _root_.me.shadaj.scalapy.readwrite.Reader[T17], r18: _root_.me.shadaj.scalapy.readwrite.Reader[T18], r19: _root_.me.shadaj.scalapy.readwrite.Reader[T19], r20: _root_.me.shadaj.scalapy.readwrite.Reader[T20], r21: _root_.me.shadaj.scalapy.readwrite.Reader[T21], r22: _root_.me.shadaj.scalapy.readwrite.Reader[T22], oWriter: _root_.me.shadaj.scalapy.readwrite.Writer[O]): _root_.me.shadaj.scalapy.readwrite.Writer[(T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, T11, T12, T13, T14, T15, T16, T17, T18, T19, T20, T21, T22) => O] = ???
}
