package torch.scalapy.readwrite

trait FunctionReaders {
  implicit def function0Reader[O](implicit oReader: _root_.torch.scalapy.readwrite.Reader[O]): _root_.torch.scalapy.readwrite.Reader[() => O] = ???

  implicit def function1Reader[T1, O](implicit w1: _root_.torch.scalapy.readwrite.Writer[T1], oReader: _root_.torch.scalapy.readwrite.Reader[O]): _root_.torch.scalapy.readwrite.Reader[T1 => O] = ???

  implicit def function2Reader[T1, T2, O](implicit w1: _root_.torch.scalapy.readwrite.Writer[T1], w2: _root_.torch.scalapy.readwrite.Writer[T2], oReader: _root_.torch.scalapy.readwrite.Reader[O]): _root_.torch.scalapy.readwrite.Reader[(T1, T2) => O] = ???

  implicit def function3Reader[T1, T2, T3, O](implicit w1: _root_.torch.scalapy.readwrite.Writer[T1], w2: _root_.torch.scalapy.readwrite.Writer[T2], w3: _root_.torch.scalapy.readwrite.Writer[T3], oReader: _root_.torch.scalapy.readwrite.Reader[O]): _root_.torch.scalapy.readwrite.Reader[(T1, T2, T3) => O] = ???

  implicit def function4Reader[T1, T2, T3, T4, O](implicit w1: _root_.torch.scalapy.readwrite.Writer[T1], w2: _root_.torch.scalapy.readwrite.Writer[T2], w3: _root_.torch.scalapy.readwrite.Writer[T3], w4: _root_.torch.scalapy.readwrite.Writer[T4], oReader: _root_.torch.scalapy.readwrite.Reader[O]): _root_.torch.scalapy.readwrite.Reader[(T1, T2, T3, T4) => O] = ???

  implicit def function5Reader[T1, T2, T3, T4, T5, O](implicit w1: _root_.torch.scalapy.readwrite.Writer[T1], w2: _root_.torch.scalapy.readwrite.Writer[T2], w3: _root_.torch.scalapy.readwrite.Writer[T3], w4: _root_.torch.scalapy.readwrite.Writer[T4], w5: _root_.torch.scalapy.readwrite.Writer[T5], oReader: _root_.torch.scalapy.readwrite.Reader[O]): _root_.torch.scalapy.readwrite.Reader[(T1, T2, T3, T4, T5) => O] = ???

  implicit def function6Reader[T1, T2, T3, T4, T5, T6, O](implicit w1: _root_.torch.scalapy.readwrite.Writer[T1], w2: _root_.torch.scalapy.readwrite.Writer[T2], w3: _root_.torch.scalapy.readwrite.Writer[T3], w4: _root_.torch.scalapy.readwrite.Writer[T4], w5: _root_.torch.scalapy.readwrite.Writer[T5], w6: _root_.torch.scalapy.readwrite.Writer[T6], oReader: _root_.torch.scalapy.readwrite.Reader[O]): _root_.torch.scalapy.readwrite.Reader[(T1, T2, T3, T4, T5, T6) => O] = ???

  implicit def function7Reader[T1, T2, T3, T4, T5, T6, T7, O](implicit w1: _root_.torch.scalapy.readwrite.Writer[T1], w2: _root_.torch.scalapy.readwrite.Writer[T2], w3: _root_.torch.scalapy.readwrite.Writer[T3], w4: _root_.torch.scalapy.readwrite.Writer[T4], w5: _root_.torch.scalapy.readwrite.Writer[T5], w6: _root_.torch.scalapy.readwrite.Writer[T6], w7: _root_.torch.scalapy.readwrite.Writer[T7], oReader: _root_.torch.scalapy.readwrite.Reader[O]): _root_.torch.scalapy.readwrite.Reader[(T1, T2, T3, T4, T5, T6, T7) => O] = ???

  implicit def function8Reader[T1, T2, T3, T4, T5, T6, T7, T8, O](implicit w1: _root_.torch.scalapy.readwrite.Writer[T1], w2: _root_.torch.scalapy.readwrite.Writer[T2], w3: _root_.torch.scalapy.readwrite.Writer[T3], w4: _root_.torch.scalapy.readwrite.Writer[T4], w5: _root_.torch.scalapy.readwrite.Writer[T5], w6: _root_.torch.scalapy.readwrite.Writer[T6], w7: _root_.torch.scalapy.readwrite.Writer[T7], w8: _root_.torch.scalapy.readwrite.Writer[T8], oReader: _root_.torch.scalapy.readwrite.Reader[O]): _root_.torch.scalapy.readwrite.Reader[(T1, T2, T3, T4, T5, T6, T7, T8) => O] = ???

  implicit def function9Reader[T1, T2, T3, T4, T5, T6, T7, T8, T9, O](implicit w1: _root_.torch.scalapy.readwrite.Writer[T1], w2: _root_.torch.scalapy.readwrite.Writer[T2], w3: _root_.torch.scalapy.readwrite.Writer[T3], w4: _root_.torch.scalapy.readwrite.Writer[T4], w5: _root_.torch.scalapy.readwrite.Writer[T5], w6: _root_.torch.scalapy.readwrite.Writer[T6], w7: _root_.torch.scalapy.readwrite.Writer[T7], w8: _root_.torch.scalapy.readwrite.Writer[T8], w9: _root_.torch.scalapy.readwrite.Writer[T9], oReader: _root_.torch.scalapy.readwrite.Reader[O]): _root_.torch.scalapy.readwrite.Reader[(T1, T2, T3, T4, T5, T6, T7, T8, T9) => O] = ???

  implicit def function10Reader[T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, O](implicit w1: _root_.torch.scalapy.readwrite.Writer[T1], w2: _root_.torch.scalapy.readwrite.Writer[T2], w3: _root_.torch.scalapy.readwrite.Writer[T3], w4: _root_.torch.scalapy.readwrite.Writer[T4], w5: _root_.torch.scalapy.readwrite.Writer[T5], w6: _root_.torch.scalapy.readwrite.Writer[T6], w7: _root_.torch.scalapy.readwrite.Writer[T7], w8: _root_.torch.scalapy.readwrite.Writer[T8], w9: _root_.torch.scalapy.readwrite.Writer[T9], w10: _root_.torch.scalapy.readwrite.Writer[T10], oReader: _root_.torch.scalapy.readwrite.Reader[O]): _root_.torch.scalapy.readwrite.Reader[(T1, T2, T3, T4, T5, T6, T7, T8, T9, T10) => O] = ???

  implicit def function11Reader[T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, T11, O](implicit w1: _root_.torch.scalapy.readwrite.Writer[T1], w2: _root_.torch.scalapy.readwrite.Writer[T2], w3: _root_.torch.scalapy.readwrite.Writer[T3], w4: _root_.torch.scalapy.readwrite.Writer[T4], w5: _root_.torch.scalapy.readwrite.Writer[T5], w6: _root_.torch.scalapy.readwrite.Writer[T6], w7: _root_.torch.scalapy.readwrite.Writer[T7], w8: _root_.torch.scalapy.readwrite.Writer[T8], w9: _root_.torch.scalapy.readwrite.Writer[T9], w10: _root_.torch.scalapy.readwrite.Writer[T10], w11: _root_.torch.scalapy.readwrite.Writer[T11], oReader: _root_.torch.scalapy.readwrite.Reader[O]): _root_.torch.scalapy.readwrite.Reader[(T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, T11) => O] = ???

  implicit def function12Reader[T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, T11, T12, O](implicit w1: _root_.torch.scalapy.readwrite.Writer[T1], w2: _root_.torch.scalapy.readwrite.Writer[T2], w3: _root_.torch.scalapy.readwrite.Writer[T3], w4: _root_.torch.scalapy.readwrite.Writer[T4], w5: _root_.torch.scalapy.readwrite.Writer[T5], w6: _root_.torch.scalapy.readwrite.Writer[T6], w7: _root_.torch.scalapy.readwrite.Writer[T7], w8: _root_.torch.scalapy.readwrite.Writer[T8], w9: _root_.torch.scalapy.readwrite.Writer[T9], w10: _root_.torch.scalapy.readwrite.Writer[T10], w11: _root_.torch.scalapy.readwrite.Writer[T11], w12: _root_.torch.scalapy.readwrite.Writer[T12], oReader: _root_.torch.scalapy.readwrite.Reader[O]): _root_.torch.scalapy.readwrite.Reader[(T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, T11, T12) => O] = ???

  implicit def function13Reader[T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, T11, T12, T13, O](implicit w1: _root_.torch.scalapy.readwrite.Writer[T1], w2: _root_.torch.scalapy.readwrite.Writer[T2], w3: _root_.torch.scalapy.readwrite.Writer[T3], w4: _root_.torch.scalapy.readwrite.Writer[T4], w5: _root_.torch.scalapy.readwrite.Writer[T5], w6: _root_.torch.scalapy.readwrite.Writer[T6], w7: _root_.torch.scalapy.readwrite.Writer[T7], w8: _root_.torch.scalapy.readwrite.Writer[T8], w9: _root_.torch.scalapy.readwrite.Writer[T9], w10: _root_.torch.scalapy.readwrite.Writer[T10], w11: _root_.torch.scalapy.readwrite.Writer[T11], w12: _root_.torch.scalapy.readwrite.Writer[T12], w13: _root_.torch.scalapy.readwrite.Writer[T13], oReader: _root_.torch.scalapy.readwrite.Reader[O]): _root_.torch.scalapy.readwrite.Reader[(T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, T11, T12, T13) => O] = ???

  implicit def function14Reader[T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, T11, T12, T13, T14, O](implicit w1: _root_.torch.scalapy.readwrite.Writer[T1], w2: _root_.torch.scalapy.readwrite.Writer[T2], w3: _root_.torch.scalapy.readwrite.Writer[T3], w4: _root_.torch.scalapy.readwrite.Writer[T4], w5: _root_.torch.scalapy.readwrite.Writer[T5], w6: _root_.torch.scalapy.readwrite.Writer[T6], w7: _root_.torch.scalapy.readwrite.Writer[T7], w8: _root_.torch.scalapy.readwrite.Writer[T8], w9: _root_.torch.scalapy.readwrite.Writer[T9], w10: _root_.torch.scalapy.readwrite.Writer[T10], w11: _root_.torch.scalapy.readwrite.Writer[T11], w12: _root_.torch.scalapy.readwrite.Writer[T12], w13: _root_.torch.scalapy.readwrite.Writer[T13], w14: _root_.torch.scalapy.readwrite.Writer[T14], oReader: _root_.torch.scalapy.readwrite.Reader[O]): _root_.torch.scalapy.readwrite.Reader[(T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, T11, T12, T13, T14) => O] = ???

  implicit def function15Reader[T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, T11, T12, T13, T14, T15, O](implicit w1: _root_.torch.scalapy.readwrite.Writer[T1], w2: _root_.torch.scalapy.readwrite.Writer[T2], w3: _root_.torch.scalapy.readwrite.Writer[T3], w4: _root_.torch.scalapy.readwrite.Writer[T4], w5: _root_.torch.scalapy.readwrite.Writer[T5], w6: _root_.torch.scalapy.readwrite.Writer[T6], w7: _root_.torch.scalapy.readwrite.Writer[T7], w8: _root_.torch.scalapy.readwrite.Writer[T8], w9: _root_.torch.scalapy.readwrite.Writer[T9], w10: _root_.torch.scalapy.readwrite.Writer[T10], w11: _root_.torch.scalapy.readwrite.Writer[T11], w12: _root_.torch.scalapy.readwrite.Writer[T12], w13: _root_.torch.scalapy.readwrite.Writer[T13], w14: _root_.torch.scalapy.readwrite.Writer[T14], w15: _root_.torch.scalapy.readwrite.Writer[T15], oReader: _root_.torch.scalapy.readwrite.Reader[O]): _root_.torch.scalapy.readwrite.Reader[(T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, T11, T12, T13, T14, T15) => O] = ???

  implicit def function16Reader[T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, T11, T12, T13, T14, T15, T16, O](implicit w1: _root_.torch.scalapy.readwrite.Writer[T1], w2: _root_.torch.scalapy.readwrite.Writer[T2], w3: _root_.torch.scalapy.readwrite.Writer[T3], w4: _root_.torch.scalapy.readwrite.Writer[T4], w5: _root_.torch.scalapy.readwrite.Writer[T5], w6: _root_.torch.scalapy.readwrite.Writer[T6], w7: _root_.torch.scalapy.readwrite.Writer[T7], w8: _root_.torch.scalapy.readwrite.Writer[T8], w9: _root_.torch.scalapy.readwrite.Writer[T9], w10: _root_.torch.scalapy.readwrite.Writer[T10], w11: _root_.torch.scalapy.readwrite.Writer[T11], w12: _root_.torch.scalapy.readwrite.Writer[T12], w13: _root_.torch.scalapy.readwrite.Writer[T13], w14: _root_.torch.scalapy.readwrite.Writer[T14], w15: _root_.torch.scalapy.readwrite.Writer[T15], w16: _root_.torch.scalapy.readwrite.Writer[T16], oReader: _root_.torch.scalapy.readwrite.Reader[O]): _root_.torch.scalapy.readwrite.Reader[(T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, T11, T12, T13, T14, T15, T16) => O] = ???

  implicit def function17Reader[T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, T11, T12, T13, T14, T15, T16, T17, O](implicit w1: _root_.torch.scalapy.readwrite.Writer[T1], w2: _root_.torch.scalapy.readwrite.Writer[T2], w3: _root_.torch.scalapy.readwrite.Writer[T3], w4: _root_.torch.scalapy.readwrite.Writer[T4], w5: _root_.torch.scalapy.readwrite.Writer[T5], w6: _root_.torch.scalapy.readwrite.Writer[T6], w7: _root_.torch.scalapy.readwrite.Writer[T7], w8: _root_.torch.scalapy.readwrite.Writer[T8], w9: _root_.torch.scalapy.readwrite.Writer[T9], w10: _root_.torch.scalapy.readwrite.Writer[T10], w11: _root_.torch.scalapy.readwrite.Writer[T11], w12: _root_.torch.scalapy.readwrite.Writer[T12], w13: _root_.torch.scalapy.readwrite.Writer[T13], w14: _root_.torch.scalapy.readwrite.Writer[T14], w15: _root_.torch.scalapy.readwrite.Writer[T15], w16: _root_.torch.scalapy.readwrite.Writer[T16], w17: _root_.torch.scalapy.readwrite.Writer[T17], oReader: _root_.torch.scalapy.readwrite.Reader[O]): _root_.torch.scalapy.readwrite.Reader[(T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, T11, T12, T13, T14, T15, T16, T17) => O] = ???

  implicit def function18Reader[T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, T11, T12, T13, T14, T15, T16, T17, T18, O](implicit w1: _root_.torch.scalapy.readwrite.Writer[T1], w2: _root_.torch.scalapy.readwrite.Writer[T2], w3: _root_.torch.scalapy.readwrite.Writer[T3], w4: _root_.torch.scalapy.readwrite.Writer[T4], w5: _root_.torch.scalapy.readwrite.Writer[T5], w6: _root_.torch.scalapy.readwrite.Writer[T6], w7: _root_.torch.scalapy.readwrite.Writer[T7], w8: _root_.torch.scalapy.readwrite.Writer[T8], w9: _root_.torch.scalapy.readwrite.Writer[T9], w10: _root_.torch.scalapy.readwrite.Writer[T10], w11: _root_.torch.scalapy.readwrite.Writer[T11], w12: _root_.torch.scalapy.readwrite.Writer[T12], w13: _root_.torch.scalapy.readwrite.Writer[T13], w14: _root_.torch.scalapy.readwrite.Writer[T14], w15: _root_.torch.scalapy.readwrite.Writer[T15], w16: _root_.torch.scalapy.readwrite.Writer[T16], w17: _root_.torch.scalapy.readwrite.Writer[T17], w18: _root_.torch.scalapy.readwrite.Writer[T18], oReader: _root_.torch.scalapy.readwrite.Reader[O]): _root_.torch.scalapy.readwrite.Reader[(T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, T11, T12, T13, T14, T15, T16, T17, T18) => O] = ???

  implicit def function19Reader[T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, T11, T12, T13, T14, T15, T16, T17, T18, T19, O](implicit w1: _root_.torch.scalapy.readwrite.Writer[T1], w2: _root_.torch.scalapy.readwrite.Writer[T2], w3: _root_.torch.scalapy.readwrite.Writer[T3], w4: _root_.torch.scalapy.readwrite.Writer[T4], w5: _root_.torch.scalapy.readwrite.Writer[T5], w6: _root_.torch.scalapy.readwrite.Writer[T6], w7: _root_.torch.scalapy.readwrite.Writer[T7], w8: _root_.torch.scalapy.readwrite.Writer[T8], w9: _root_.torch.scalapy.readwrite.Writer[T9], w10: _root_.torch.scalapy.readwrite.Writer[T10], w11: _root_.torch.scalapy.readwrite.Writer[T11], w12: _root_.torch.scalapy.readwrite.Writer[T12], w13: _root_.torch.scalapy.readwrite.Writer[T13], w14: _root_.torch.scalapy.readwrite.Writer[T14], w15: _root_.torch.scalapy.readwrite.Writer[T15], w16: _root_.torch.scalapy.readwrite.Writer[T16], w17: _root_.torch.scalapy.readwrite.Writer[T17], w18: _root_.torch.scalapy.readwrite.Writer[T18], w19: _root_.torch.scalapy.readwrite.Writer[T19], oReader: _root_.torch.scalapy.readwrite.Reader[O]): _root_.torch.scalapy.readwrite.Reader[(T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, T11, T12, T13, T14, T15, T16, T17, T18, T19) => O] = ???

  implicit def function20Reader[T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, T11, T12, T13, T14, T15, T16, T17, T18, T19, T20, O](implicit w1: _root_.torch.scalapy.readwrite.Writer[T1], w2: _root_.torch.scalapy.readwrite.Writer[T2], w3: _root_.torch.scalapy.readwrite.Writer[T3], w4: _root_.torch.scalapy.readwrite.Writer[T4], w5: _root_.torch.scalapy.readwrite.Writer[T5], w6: _root_.torch.scalapy.readwrite.Writer[T6], w7: _root_.torch.scalapy.readwrite.Writer[T7], w8: _root_.torch.scalapy.readwrite.Writer[T8], w9: _root_.torch.scalapy.readwrite.Writer[T9], w10: _root_.torch.scalapy.readwrite.Writer[T10], w11: _root_.torch.scalapy.readwrite.Writer[T11], w12: _root_.torch.scalapy.readwrite.Writer[T12], w13: _root_.torch.scalapy.readwrite.Writer[T13], w14: _root_.torch.scalapy.readwrite.Writer[T14], w15: _root_.torch.scalapy.readwrite.Writer[T15], w16: _root_.torch.scalapy.readwrite.Writer[T16], w17: _root_.torch.scalapy.readwrite.Writer[T17], w18: _root_.torch.scalapy.readwrite.Writer[T18], w19: _root_.torch.scalapy.readwrite.Writer[T19], w20: _root_.torch.scalapy.readwrite.Writer[T20], oReader: _root_.torch.scalapy.readwrite.Reader[O]): _root_.torch.scalapy.readwrite.Reader[(T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, T11, T12, T13, T14, T15, T16, T17, T18, T19, T20) => O] = ???

  implicit def function21Reader[T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, T11, T12, T13, T14, T15, T16, T17, T18, T19, T20, T21, O](implicit w1: _root_.torch.scalapy.readwrite.Writer[T1], w2: _root_.torch.scalapy.readwrite.Writer[T2], w3: _root_.torch.scalapy.readwrite.Writer[T3], w4: _root_.torch.scalapy.readwrite.Writer[T4], w5: _root_.torch.scalapy.readwrite.Writer[T5], w6: _root_.torch.scalapy.readwrite.Writer[T6], w7: _root_.torch.scalapy.readwrite.Writer[T7], w8: _root_.torch.scalapy.readwrite.Writer[T8], w9: _root_.torch.scalapy.readwrite.Writer[T9], w10: _root_.torch.scalapy.readwrite.Writer[T10], w11: _root_.torch.scalapy.readwrite.Writer[T11], w12: _root_.torch.scalapy.readwrite.Writer[T12], w13: _root_.torch.scalapy.readwrite.Writer[T13], w14: _root_.torch.scalapy.readwrite.Writer[T14], w15: _root_.torch.scalapy.readwrite.Writer[T15], w16: _root_.torch.scalapy.readwrite.Writer[T16], w17: _root_.torch.scalapy.readwrite.Writer[T17], w18: _root_.torch.scalapy.readwrite.Writer[T18], w19: _root_.torch.scalapy.readwrite.Writer[T19], w20: _root_.torch.scalapy.readwrite.Writer[T20], w21: _root_.torch.scalapy.readwrite.Writer[T21], oReader: _root_.torch.scalapy.readwrite.Reader[O]): _root_.torch.scalapy.readwrite.Reader[(T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, T11, T12, T13, T14, T15, T16, T17, T18, T19, T20, T21) => O] = ???

  implicit def function22Reader[T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, T11, T12, T13, T14, T15, T16, T17, T18, T19, T20, T21, T22, O](implicit w1: _root_.torch.scalapy.readwrite.Writer[T1], w2: _root_.torch.scalapy.readwrite.Writer[T2], w3: _root_.torch.scalapy.readwrite.Writer[T3], w4: _root_.torch.scalapy.readwrite.Writer[T4], w5: _root_.torch.scalapy.readwrite.Writer[T5], w6: _root_.torch.scalapy.readwrite.Writer[T6], w7: _root_.torch.scalapy.readwrite.Writer[T7], w8: _root_.torch.scalapy.readwrite.Writer[T8], w9: _root_.torch.scalapy.readwrite.Writer[T9], w10: _root_.torch.scalapy.readwrite.Writer[T10], w11: _root_.torch.scalapy.readwrite.Writer[T11], w12: _root_.torch.scalapy.readwrite.Writer[T12], w13: _root_.torch.scalapy.readwrite.Writer[T13], w14: _root_.torch.scalapy.readwrite.Writer[T14], w15: _root_.torch.scalapy.readwrite.Writer[T15], w16: _root_.torch.scalapy.readwrite.Writer[T16], w17: _root_.torch.scalapy.readwrite.Writer[T17], w18: _root_.torch.scalapy.readwrite.Writer[T18], w19: _root_.torch.scalapy.readwrite.Writer[T19], w20: _root_.torch.scalapy.readwrite.Writer[T20], w21: _root_.torch.scalapy.readwrite.Writer[T21], w22: _root_.torch.scalapy.readwrite.Writer[T22], oReader: _root_.torch.scalapy.readwrite.Reader[O]): _root_.torch.scalapy.readwrite.Reader[(T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, T11, T12, T13, T14, T15, T16, T17, T18, T19, T20, T21, T22) => O] = ???
}
