package torch.scalapy.readwrite

trait TupleWriters {
  implicit def tuple2Writer[T1, T2](implicit r1: _root_.torch.scalapy.readwrite.Writer[T1], r2: _root_.torch.scalapy.readwrite.Writer[T2]): _root_.torch.scalapy.readwrite.Writer[(T1, T2)] = ???

  implicit def tuple3Writer[T1, T2, T3](implicit r1: _root_.torch.scalapy.readwrite.Writer[T1], r2: _root_.torch.scalapy.readwrite.Writer[T2], r3: _root_.torch.scalapy.readwrite.Writer[T3]): _root_.torch.scalapy.readwrite.Writer[(T1, T2, T3)] = ???

  implicit def tuple4Writer[T1, T2, T3, T4](implicit r1: _root_.torch.scalapy.readwrite.Writer[T1], r2: _root_.torch.scalapy.readwrite.Writer[T2], r3: _root_.torch.scalapy.readwrite.Writer[T3], r4: _root_.torch.scalapy.readwrite.Writer[T4]): _root_.torch.scalapy.readwrite.Writer[(T1, T2, T3, T4)] = ???

  implicit def tuple5Writer[T1, T2, T3, T4, T5](implicit r1: _root_.torch.scalapy.readwrite.Writer[T1], r2: _root_.torch.scalapy.readwrite.Writer[T2], r3: _root_.torch.scalapy.readwrite.Writer[T3], r4: _root_.torch.scalapy.readwrite.Writer[T4], r5: _root_.torch.scalapy.readwrite.Writer[T5]): _root_.torch.scalapy.readwrite.Writer[(T1, T2, T3, T4, T5)] = ???

  implicit def tuple6Writer[T1, T2, T3, T4, T5, T6](implicit r1: _root_.torch.scalapy.readwrite.Writer[T1], r2: _root_.torch.scalapy.readwrite.Writer[T2], r3: _root_.torch.scalapy.readwrite.Writer[T3], r4: _root_.torch.scalapy.readwrite.Writer[T4], r5: _root_.torch.scalapy.readwrite.Writer[T5], r6: _root_.torch.scalapy.readwrite.Writer[T6]): _root_.torch.scalapy.readwrite.Writer[(T1, T2, T3, T4, T5, T6)] = ???

  implicit def tuple7Writer[T1, T2, T3, T4, T5, T6, T7](implicit r1: _root_.torch.scalapy.readwrite.Writer[T1], r2: _root_.torch.scalapy.readwrite.Writer[T2], r3: _root_.torch.scalapy.readwrite.Writer[T3], r4: _root_.torch.scalapy.readwrite.Writer[T4], r5: _root_.torch.scalapy.readwrite.Writer[T5], r6: _root_.torch.scalapy.readwrite.Writer[T6], r7: _root_.torch.scalapy.readwrite.Writer[T7]): _root_.torch.scalapy.readwrite.Writer[(T1, T2, T3, T4, T5, T6, T7)] = ???

  implicit def tuple8Writer[T1, T2, T3, T4, T5, T6, T7, T8](implicit r1: _root_.torch.scalapy.readwrite.Writer[T1], r2: _root_.torch.scalapy.readwrite.Writer[T2], r3: _root_.torch.scalapy.readwrite.Writer[T3], r4: _root_.torch.scalapy.readwrite.Writer[T4], r5: _root_.torch.scalapy.readwrite.Writer[T5], r6: _root_.torch.scalapy.readwrite.Writer[T6], r7: _root_.torch.scalapy.readwrite.Writer[T7], r8: _root_.torch.scalapy.readwrite.Writer[T8]): _root_.torch.scalapy.readwrite.Writer[(T1, T2, T3, T4, T5, T6, T7, T8)] = ???

  implicit def tuple9Writer[T1, T2, T3, T4, T5, T6, T7, T8, T9](implicit r1: _root_.torch.scalapy.readwrite.Writer[T1], r2: _root_.torch.scalapy.readwrite.Writer[T2], r3: _root_.torch.scalapy.readwrite.Writer[T3], r4: _root_.torch.scalapy.readwrite.Writer[T4], r5: _root_.torch.scalapy.readwrite.Writer[T5], r6: _root_.torch.scalapy.readwrite.Writer[T6], r7: _root_.torch.scalapy.readwrite.Writer[T7], r8: _root_.torch.scalapy.readwrite.Writer[T8], r9: _root_.torch.scalapy.readwrite.Writer[T9]): _root_.torch.scalapy.readwrite.Writer[(T1, T2, T3, T4, T5, T6, T7, T8, T9)] = ???

  implicit def tuple10Writer[T1, T2, T3, T4, T5, T6, T7, T8, T9, T10](implicit r1: _root_.torch.scalapy.readwrite.Writer[T1], r2: _root_.torch.scalapy.readwrite.Writer[T2], r3: _root_.torch.scalapy.readwrite.Writer[T3], r4: _root_.torch.scalapy.readwrite.Writer[T4], r5: _root_.torch.scalapy.readwrite.Writer[T5], r6: _root_.torch.scalapy.readwrite.Writer[T6], r7: _root_.torch.scalapy.readwrite.Writer[T7], r8: _root_.torch.scalapy.readwrite.Writer[T8], r9: _root_.torch.scalapy.readwrite.Writer[T9], r10: _root_.torch.scalapy.readwrite.Writer[T10]): _root_.torch.scalapy.readwrite.Writer[(T1, T2, T3, T4, T5, T6, T7, T8, T9, T10)] = ???

  implicit def tuple11Writer[T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, T11](implicit r1: _root_.torch.scalapy.readwrite.Writer[T1], r2: _root_.torch.scalapy.readwrite.Writer[T2], r3: _root_.torch.scalapy.readwrite.Writer[T3], r4: _root_.torch.scalapy.readwrite.Writer[T4], r5: _root_.torch.scalapy.readwrite.Writer[T5], r6: _root_.torch.scalapy.readwrite.Writer[T6], r7: _root_.torch.scalapy.readwrite.Writer[T7], r8: _root_.torch.scalapy.readwrite.Writer[T8], r9: _root_.torch.scalapy.readwrite.Writer[T9], r10: _root_.torch.scalapy.readwrite.Writer[T10], r11: _root_.torch.scalapy.readwrite.Writer[T11]): _root_.torch.scalapy.readwrite.Writer[(T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, T11)] = ???

  implicit def tuple12Writer[T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, T11, T12](implicit r1: _root_.torch.scalapy.readwrite.Writer[T1], r2: _root_.torch.scalapy.readwrite.Writer[T2], r3: _root_.torch.scalapy.readwrite.Writer[T3], r4: _root_.torch.scalapy.readwrite.Writer[T4], r5: _root_.torch.scalapy.readwrite.Writer[T5], r6: _root_.torch.scalapy.readwrite.Writer[T6], r7: _root_.torch.scalapy.readwrite.Writer[T7], r8: _root_.torch.scalapy.readwrite.Writer[T8], r9: _root_.torch.scalapy.readwrite.Writer[T9], r10: _root_.torch.scalapy.readwrite.Writer[T10], r11: _root_.torch.scalapy.readwrite.Writer[T11], r12: _root_.torch.scalapy.readwrite.Writer[T12]): _root_.torch.scalapy.readwrite.Writer[(T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, T11, T12)] = ???

  implicit def tuple13Writer[T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, T11, T12, T13](implicit r1: _root_.torch.scalapy.readwrite.Writer[T1], r2: _root_.torch.scalapy.readwrite.Writer[T2], r3: _root_.torch.scalapy.readwrite.Writer[T3], r4: _root_.torch.scalapy.readwrite.Writer[T4], r5: _root_.torch.scalapy.readwrite.Writer[T5], r6: _root_.torch.scalapy.readwrite.Writer[T6], r7: _root_.torch.scalapy.readwrite.Writer[T7], r8: _root_.torch.scalapy.readwrite.Writer[T8], r9: _root_.torch.scalapy.readwrite.Writer[T9], r10: _root_.torch.scalapy.readwrite.Writer[T10], r11: _root_.torch.scalapy.readwrite.Writer[T11], r12: _root_.torch.scalapy.readwrite.Writer[T12], r13: _root_.torch.scalapy.readwrite.Writer[T13]): _root_.torch.scalapy.readwrite.Writer[(T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, T11, T12, T13)] = ???

  implicit def tuple14Writer[T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, T11, T12, T13, T14](implicit r1: _root_.torch.scalapy.readwrite.Writer[T1], r2: _root_.torch.scalapy.readwrite.Writer[T2], r3: _root_.torch.scalapy.readwrite.Writer[T3], r4: _root_.torch.scalapy.readwrite.Writer[T4], r5: _root_.torch.scalapy.readwrite.Writer[T5], r6: _root_.torch.scalapy.readwrite.Writer[T6], r7: _root_.torch.scalapy.readwrite.Writer[T7], r8: _root_.torch.scalapy.readwrite.Writer[T8], r9: _root_.torch.scalapy.readwrite.Writer[T9], r10: _root_.torch.scalapy.readwrite.Writer[T10], r11: _root_.torch.scalapy.readwrite.Writer[T11], r12: _root_.torch.scalapy.readwrite.Writer[T12], r13: _root_.torch.scalapy.readwrite.Writer[T13], r14: _root_.torch.scalapy.readwrite.Writer[T14]): _root_.torch.scalapy.readwrite.Writer[(T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, T11, T12, T13, T14)] = ???

  implicit def tuple15Writer[T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, T11, T12, T13, T14, T15](implicit r1: _root_.torch.scalapy.readwrite.Writer[T1], r2: _root_.torch.scalapy.readwrite.Writer[T2], r3: _root_.torch.scalapy.readwrite.Writer[T3], r4: _root_.torch.scalapy.readwrite.Writer[T4], r5: _root_.torch.scalapy.readwrite.Writer[T5], r6: _root_.torch.scalapy.readwrite.Writer[T6], r7: _root_.torch.scalapy.readwrite.Writer[T7], r8: _root_.torch.scalapy.readwrite.Writer[T8], r9: _root_.torch.scalapy.readwrite.Writer[T9], r10: _root_.torch.scalapy.readwrite.Writer[T10], r11: _root_.torch.scalapy.readwrite.Writer[T11], r12: _root_.torch.scalapy.readwrite.Writer[T12], r13: _root_.torch.scalapy.readwrite.Writer[T13], r14: _root_.torch.scalapy.readwrite.Writer[T14], r15: _root_.torch.scalapy.readwrite.Writer[T15]): _root_.torch.scalapy.readwrite.Writer[(T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, T11, T12, T13, T14, T15)] = ???

  implicit def tuple16Writer[T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, T11, T12, T13, T14, T15, T16](implicit r1: _root_.torch.scalapy.readwrite.Writer[T1], r2: _root_.torch.scalapy.readwrite.Writer[T2], r3: _root_.torch.scalapy.readwrite.Writer[T3], r4: _root_.torch.scalapy.readwrite.Writer[T4], r5: _root_.torch.scalapy.readwrite.Writer[T5], r6: _root_.torch.scalapy.readwrite.Writer[T6], r7: _root_.torch.scalapy.readwrite.Writer[T7], r8: _root_.torch.scalapy.readwrite.Writer[T8], r9: _root_.torch.scalapy.readwrite.Writer[T9], r10: _root_.torch.scalapy.readwrite.Writer[T10], r11: _root_.torch.scalapy.readwrite.Writer[T11], r12: _root_.torch.scalapy.readwrite.Writer[T12], r13: _root_.torch.scalapy.readwrite.Writer[T13], r14: _root_.torch.scalapy.readwrite.Writer[T14], r15: _root_.torch.scalapy.readwrite.Writer[T15], r16: _root_.torch.scalapy.readwrite.Writer[T16]): _root_.torch.scalapy.readwrite.Writer[(T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, T11, T12, T13, T14, T15, T16)] = ???

  implicit def tuple17Writer[T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, T11, T12, T13, T14, T15, T16, T17](implicit r1: _root_.torch.scalapy.readwrite.Writer[T1], r2: _root_.torch.scalapy.readwrite.Writer[T2], r3: _root_.torch.scalapy.readwrite.Writer[T3], r4: _root_.torch.scalapy.readwrite.Writer[T4], r5: _root_.torch.scalapy.readwrite.Writer[T5], r6: _root_.torch.scalapy.readwrite.Writer[T6], r7: _root_.torch.scalapy.readwrite.Writer[T7], r8: _root_.torch.scalapy.readwrite.Writer[T8], r9: _root_.torch.scalapy.readwrite.Writer[T9], r10: _root_.torch.scalapy.readwrite.Writer[T10], r11: _root_.torch.scalapy.readwrite.Writer[T11], r12: _root_.torch.scalapy.readwrite.Writer[T12], r13: _root_.torch.scalapy.readwrite.Writer[T13], r14: _root_.torch.scalapy.readwrite.Writer[T14], r15: _root_.torch.scalapy.readwrite.Writer[T15], r16: _root_.torch.scalapy.readwrite.Writer[T16], r17: _root_.torch.scalapy.readwrite.Writer[T17]): _root_.torch.scalapy.readwrite.Writer[(T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, T11, T12, T13, T14, T15, T16, T17)] = ???

  implicit def tuple18Writer[T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, T11, T12, T13, T14, T15, T16, T17, T18](implicit r1: _root_.torch.scalapy.readwrite.Writer[T1], r2: _root_.torch.scalapy.readwrite.Writer[T2], r3: _root_.torch.scalapy.readwrite.Writer[T3], r4: _root_.torch.scalapy.readwrite.Writer[T4], r5: _root_.torch.scalapy.readwrite.Writer[T5], r6: _root_.torch.scalapy.readwrite.Writer[T6], r7: _root_.torch.scalapy.readwrite.Writer[T7], r8: _root_.torch.scalapy.readwrite.Writer[T8], r9: _root_.torch.scalapy.readwrite.Writer[T9], r10: _root_.torch.scalapy.readwrite.Writer[T10], r11: _root_.torch.scalapy.readwrite.Writer[T11], r12: _root_.torch.scalapy.readwrite.Writer[T12], r13: _root_.torch.scalapy.readwrite.Writer[T13], r14: _root_.torch.scalapy.readwrite.Writer[T14], r15: _root_.torch.scalapy.readwrite.Writer[T15], r16: _root_.torch.scalapy.readwrite.Writer[T16], r17: _root_.torch.scalapy.readwrite.Writer[T17], r18: _root_.torch.scalapy.readwrite.Writer[T18]): _root_.torch.scalapy.readwrite.Writer[(T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, T11, T12, T13, T14, T15, T16, T17, T18)] = ???

  implicit def tuple19Writer[T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, T11, T12, T13, T14, T15, T16, T17, T18, T19](implicit r1: _root_.torch.scalapy.readwrite.Writer[T1], r2: _root_.torch.scalapy.readwrite.Writer[T2], r3: _root_.torch.scalapy.readwrite.Writer[T3], r4: _root_.torch.scalapy.readwrite.Writer[T4], r5: _root_.torch.scalapy.readwrite.Writer[T5], r6: _root_.torch.scalapy.readwrite.Writer[T6], r7: _root_.torch.scalapy.readwrite.Writer[T7], r8: _root_.torch.scalapy.readwrite.Writer[T8], r9: _root_.torch.scalapy.readwrite.Writer[T9], r10: _root_.torch.scalapy.readwrite.Writer[T10], r11: _root_.torch.scalapy.readwrite.Writer[T11], r12: _root_.torch.scalapy.readwrite.Writer[T12], r13: _root_.torch.scalapy.readwrite.Writer[T13], r14: _root_.torch.scalapy.readwrite.Writer[T14], r15: _root_.torch.scalapy.readwrite.Writer[T15], r16: _root_.torch.scalapy.readwrite.Writer[T16], r17: _root_.torch.scalapy.readwrite.Writer[T17], r18: _root_.torch.scalapy.readwrite.Writer[T18], r19: _root_.torch.scalapy.readwrite.Writer[T19]): _root_.torch.scalapy.readwrite.Writer[(T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, T11, T12, T13, T14, T15, T16, T17, T18, T19)] = ???

  implicit def tuple20Writer[T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, T11, T12, T13, T14, T15, T16, T17, T18, T19, T20](implicit r1: _root_.torch.scalapy.readwrite.Writer[T1], r2: _root_.torch.scalapy.readwrite.Writer[T2], r3: _root_.torch.scalapy.readwrite.Writer[T3], r4: _root_.torch.scalapy.readwrite.Writer[T4], r5: _root_.torch.scalapy.readwrite.Writer[T5], r6: _root_.torch.scalapy.readwrite.Writer[T6], r7: _root_.torch.scalapy.readwrite.Writer[T7], r8: _root_.torch.scalapy.readwrite.Writer[T8], r9: _root_.torch.scalapy.readwrite.Writer[T9], r10: _root_.torch.scalapy.readwrite.Writer[T10], r11: _root_.torch.scalapy.readwrite.Writer[T11], r12: _root_.torch.scalapy.readwrite.Writer[T12], r13: _root_.torch.scalapy.readwrite.Writer[T13], r14: _root_.torch.scalapy.readwrite.Writer[T14], r15: _root_.torch.scalapy.readwrite.Writer[T15], r16: _root_.torch.scalapy.readwrite.Writer[T16], r17: _root_.torch.scalapy.readwrite.Writer[T17], r18: _root_.torch.scalapy.readwrite.Writer[T18], r19: _root_.torch.scalapy.readwrite.Writer[T19], r20: _root_.torch.scalapy.readwrite.Writer[T20]): _root_.torch.scalapy.readwrite.Writer[(T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, T11, T12, T13, T14, T15, T16, T17, T18, T19, T20)] = ???

  implicit def tuple21Writer[T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, T11, T12, T13, T14, T15, T16, T17, T18, T19, T20, T21](implicit r1: _root_.torch.scalapy.readwrite.Writer[T1], r2: _root_.torch.scalapy.readwrite.Writer[T2], r3: _root_.torch.scalapy.readwrite.Writer[T3], r4: _root_.torch.scalapy.readwrite.Writer[T4], r5: _root_.torch.scalapy.readwrite.Writer[T5], r6: _root_.torch.scalapy.readwrite.Writer[T6], r7: _root_.torch.scalapy.readwrite.Writer[T7], r8: _root_.torch.scalapy.readwrite.Writer[T8], r9: _root_.torch.scalapy.readwrite.Writer[T9], r10: _root_.torch.scalapy.readwrite.Writer[T10], r11: _root_.torch.scalapy.readwrite.Writer[T11], r12: _root_.torch.scalapy.readwrite.Writer[T12], r13: _root_.torch.scalapy.readwrite.Writer[T13], r14: _root_.torch.scalapy.readwrite.Writer[T14], r15: _root_.torch.scalapy.readwrite.Writer[T15], r16: _root_.torch.scalapy.readwrite.Writer[T16], r17: _root_.torch.scalapy.readwrite.Writer[T17], r18: _root_.torch.scalapy.readwrite.Writer[T18], r19: _root_.torch.scalapy.readwrite.Writer[T19], r20: _root_.torch.scalapy.readwrite.Writer[T20], r21: _root_.torch.scalapy.readwrite.Writer[T21]): _root_.torch.scalapy.readwrite.Writer[(T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, T11, T12, T13, T14, T15, T16, T17, T18, T19, T20, T21)] = ???

  implicit def tuple22Writer[T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, T11, T12, T13, T14, T15, T16, T17, T18, T19, T20, T21, T22](implicit r1: _root_.torch.scalapy.readwrite.Writer[T1], r2: _root_.torch.scalapy.readwrite.Writer[T2], r3: _root_.torch.scalapy.readwrite.Writer[T3], r4: _root_.torch.scalapy.readwrite.Writer[T4], r5: _root_.torch.scalapy.readwrite.Writer[T5], r6: _root_.torch.scalapy.readwrite.Writer[T6], r7: _root_.torch.scalapy.readwrite.Writer[T7], r8: _root_.torch.scalapy.readwrite.Writer[T8], r9: _root_.torch.scalapy.readwrite.Writer[T9], r10: _root_.torch.scalapy.readwrite.Writer[T10], r11: _root_.torch.scalapy.readwrite.Writer[T11], r12: _root_.torch.scalapy.readwrite.Writer[T12], r13: _root_.torch.scalapy.readwrite.Writer[T13], r14: _root_.torch.scalapy.readwrite.Writer[T14], r15: _root_.torch.scalapy.readwrite.Writer[T15], r16: _root_.torch.scalapy.readwrite.Writer[T16], r17: _root_.torch.scalapy.readwrite.Writer[T17], r18: _root_.torch.scalapy.readwrite.Writer[T18], r19: _root_.torch.scalapy.readwrite.Writer[T19], r20: _root_.torch.scalapy.readwrite.Writer[T20], r21: _root_.torch.scalapy.readwrite.Writer[T21], r22: _root_.torch.scalapy.readwrite.Writer[T22]): _root_.torch.scalapy.readwrite.Writer[(T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, T11, T12, T13, T14, T15, T16, T17, T18, T19, T20, T21, T22)] = ???
}