package torch.scalapy.readwrite

trait TupleReaders {
  implicit def tuple2Reader[T1, T2](implicit r1: _root_.torch.scalapy.readwrite.Reader[T1], r2: _root_.torch.scalapy.readwrite.Reader[T2]): _root_.torch.scalapy.readwrite.Reader[(T1, T2)] = ???

  implicit def tuple3Reader[T1, T2, T3](implicit r1: _root_.torch.scalapy.readwrite.Reader[T1], r2: _root_.torch.scalapy.readwrite.Reader[T2], r3: _root_.torch.scalapy.readwrite.Reader[T3]): _root_.torch.scalapy.readwrite.Reader[(T1, T2, T3)] = ???

  implicit def tuple4Reader[T1, T2, T3, T4](implicit r1: _root_.torch.scalapy.readwrite.Reader[T1], r2: _root_.torch.scalapy.readwrite.Reader[T2], r3: _root_.torch.scalapy.readwrite.Reader[T3], r4: _root_.torch.scalapy.readwrite.Reader[T4]): _root_.torch.scalapy.readwrite.Reader[(T1, T2, T3, T4)] = ???

  implicit def tuple5Reader[T1, T2, T3, T4, T5](implicit r1: _root_.torch.scalapy.readwrite.Reader[T1], r2: _root_.torch.scalapy.readwrite.Reader[T2], r3: _root_.torch.scalapy.readwrite.Reader[T3], r4: _root_.torch.scalapy.readwrite.Reader[T4], r5: _root_.torch.scalapy.readwrite.Reader[T5]): _root_.torch.scalapy.readwrite.Reader[(T1, T2, T3, T4, T5)] = ???

  implicit def tuple6Reader[T1, T2, T3, T4, T5, T6](implicit r1: _root_.torch.scalapy.readwrite.Reader[T1], r2: _root_.torch.scalapy.readwrite.Reader[T2], r3: _root_.torch.scalapy.readwrite.Reader[T3], r4: _root_.torch.scalapy.readwrite.Reader[T4], r5: _root_.torch.scalapy.readwrite.Reader[T5], r6: _root_.torch.scalapy.readwrite.Reader[T6]): _root_.torch.scalapy.readwrite.Reader[(T1, T2, T3, T4, T5, T6)] = ???

  implicit def tuple7Reader[T1, T2, T3, T4, T5, T6, T7](implicit r1: _root_.torch.scalapy.readwrite.Reader[T1], r2: _root_.torch.scalapy.readwrite.Reader[T2], r3: _root_.torch.scalapy.readwrite.Reader[T3], r4: _root_.torch.scalapy.readwrite.Reader[T4], r5: _root_.torch.scalapy.readwrite.Reader[T5], r6: _root_.torch.scalapy.readwrite.Reader[T6], r7: _root_.torch.scalapy.readwrite.Reader[T7]): _root_.torch.scalapy.readwrite.Reader[(T1, T2, T3, T4, T5, T6, T7)] = ???

  implicit def tuple8Reader[T1, T2, T3, T4, T5, T6, T7, T8](implicit r1: _root_.torch.scalapy.readwrite.Reader[T1], r2: _root_.torch.scalapy.readwrite.Reader[T2], r3: _root_.torch.scalapy.readwrite.Reader[T3], r4: _root_.torch.scalapy.readwrite.Reader[T4], r5: _root_.torch.scalapy.readwrite.Reader[T5], r6: _root_.torch.scalapy.readwrite.Reader[T6], r7: _root_.torch.scalapy.readwrite.Reader[T7], r8: _root_.torch.scalapy.readwrite.Reader[T8]): _root_.torch.scalapy.readwrite.Reader[(T1, T2, T3, T4, T5, T6, T7, T8)] = ???

  implicit def tuple9Reader[T1, T2, T3, T4, T5, T6, T7, T8, T9](implicit r1: _root_.torch.scalapy.readwrite.Reader[T1], r2: _root_.torch.scalapy.readwrite.Reader[T2], r3: _root_.torch.scalapy.readwrite.Reader[T3], r4: _root_.torch.scalapy.readwrite.Reader[T4], r5: _root_.torch.scalapy.readwrite.Reader[T5], r6: _root_.torch.scalapy.readwrite.Reader[T6], r7: _root_.torch.scalapy.readwrite.Reader[T7], r8: _root_.torch.scalapy.readwrite.Reader[T8], r9: _root_.torch.scalapy.readwrite.Reader[T9]): _root_.torch.scalapy.readwrite.Reader[(T1, T2, T3, T4, T5, T6, T7, T8, T9)] = ???

  implicit def tuple10Reader[T1, T2, T3, T4, T5, T6, T7, T8, T9, T10](implicit r1: _root_.torch.scalapy.readwrite.Reader[T1], r2: _root_.torch.scalapy.readwrite.Reader[T2], r3: _root_.torch.scalapy.readwrite.Reader[T3], r4: _root_.torch.scalapy.readwrite.Reader[T4], r5: _root_.torch.scalapy.readwrite.Reader[T5], r6: _root_.torch.scalapy.readwrite.Reader[T6], r7: _root_.torch.scalapy.readwrite.Reader[T7], r8: _root_.torch.scalapy.readwrite.Reader[T8], r9: _root_.torch.scalapy.readwrite.Reader[T9], r10: _root_.torch.scalapy.readwrite.Reader[T10]): _root_.torch.scalapy.readwrite.Reader[(T1, T2, T3, T4, T5, T6, T7, T8, T9, T10)] = ???

  implicit def tuple11Reader[T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, T11](implicit r1: _root_.torch.scalapy.readwrite.Reader[T1], r2: _root_.torch.scalapy.readwrite.Reader[T2], r3: _root_.torch.scalapy.readwrite.Reader[T3], r4: _root_.torch.scalapy.readwrite.Reader[T4], r5: _root_.torch.scalapy.readwrite.Reader[T5], r6: _root_.torch.scalapy.readwrite.Reader[T6], r7: _root_.torch.scalapy.readwrite.Reader[T7], r8: _root_.torch.scalapy.readwrite.Reader[T8], r9: _root_.torch.scalapy.readwrite.Reader[T9], r10: _root_.torch.scalapy.readwrite.Reader[T10], r11: _root_.torch.scalapy.readwrite.Reader[T11]): _root_.torch.scalapy.readwrite.Reader[(T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, T11)] = ???

  implicit def tuple12Reader[T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, T11, T12](implicit r1: _root_.torch.scalapy.readwrite.Reader[T1], r2: _root_.torch.scalapy.readwrite.Reader[T2], r3: _root_.torch.scalapy.readwrite.Reader[T3], r4: _root_.torch.scalapy.readwrite.Reader[T4], r5: _root_.torch.scalapy.readwrite.Reader[T5], r6: _root_.torch.scalapy.readwrite.Reader[T6], r7: _root_.torch.scalapy.readwrite.Reader[T7], r8: _root_.torch.scalapy.readwrite.Reader[T8], r9: _root_.torch.scalapy.readwrite.Reader[T9], r10: _root_.torch.scalapy.readwrite.Reader[T10], r11: _root_.torch.scalapy.readwrite.Reader[T11], r12: _root_.torch.scalapy.readwrite.Reader[T12]): _root_.torch.scalapy.readwrite.Reader[(T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, T11, T12)] = ???

  implicit def tuple13Reader[T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, T11, T12, T13](implicit r1: _root_.torch.scalapy.readwrite.Reader[T1], r2: _root_.torch.scalapy.readwrite.Reader[T2], r3: _root_.torch.scalapy.readwrite.Reader[T3], r4: _root_.torch.scalapy.readwrite.Reader[T4], r5: _root_.torch.scalapy.readwrite.Reader[T5], r6: _root_.torch.scalapy.readwrite.Reader[T6], r7: _root_.torch.scalapy.readwrite.Reader[T7], r8: _root_.torch.scalapy.readwrite.Reader[T8], r9: _root_.torch.scalapy.readwrite.Reader[T9], r10: _root_.torch.scalapy.readwrite.Reader[T10], r11: _root_.torch.scalapy.readwrite.Reader[T11], r12: _root_.torch.scalapy.readwrite.Reader[T12], r13: _root_.torch.scalapy.readwrite.Reader[T13]): _root_.torch.scalapy.readwrite.Reader[(T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, T11, T12, T13)] = ???

  implicit def tuple14Reader[T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, T11, T12, T13, T14](implicit r1: _root_.torch.scalapy.readwrite.Reader[T1], r2: _root_.torch.scalapy.readwrite.Reader[T2], r3: _root_.torch.scalapy.readwrite.Reader[T3], r4: _root_.torch.scalapy.readwrite.Reader[T4], r5: _root_.torch.scalapy.readwrite.Reader[T5], r6: _root_.torch.scalapy.readwrite.Reader[T6], r7: _root_.torch.scalapy.readwrite.Reader[T7], r8: _root_.torch.scalapy.readwrite.Reader[T8], r9: _root_.torch.scalapy.readwrite.Reader[T9], r10: _root_.torch.scalapy.readwrite.Reader[T10], r11: _root_.torch.scalapy.readwrite.Reader[T11], r12: _root_.torch.scalapy.readwrite.Reader[T12], r13: _root_.torch.scalapy.readwrite.Reader[T13], r14: _root_.torch.scalapy.readwrite.Reader[T14]): _root_.torch.scalapy.readwrite.Reader[(T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, T11, T12, T13, T14)] = ???

  implicit def tuple15Reader[T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, T11, T12, T13, T14, T15](implicit r1: _root_.torch.scalapy.readwrite.Reader[T1], r2: _root_.torch.scalapy.readwrite.Reader[T2], r3: _root_.torch.scalapy.readwrite.Reader[T3], r4: _root_.torch.scalapy.readwrite.Reader[T4], r5: _root_.torch.scalapy.readwrite.Reader[T5], r6: _root_.torch.scalapy.readwrite.Reader[T6], r7: _root_.torch.scalapy.readwrite.Reader[T7], r8: _root_.torch.scalapy.readwrite.Reader[T8], r9: _root_.torch.scalapy.readwrite.Reader[T9], r10: _root_.torch.scalapy.readwrite.Reader[T10], r11: _root_.torch.scalapy.readwrite.Reader[T11], r12: _root_.torch.scalapy.readwrite.Reader[T12], r13: _root_.torch.scalapy.readwrite.Reader[T13], r14: _root_.torch.scalapy.readwrite.Reader[T14], r15: _root_.torch.scalapy.readwrite.Reader[T15]): _root_.torch.scalapy.readwrite.Reader[(T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, T11, T12, T13, T14, T15)] = ???

  implicit def tuple16Reader[T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, T11, T12, T13, T14, T15, T16](implicit r1: _root_.torch.scalapy.readwrite.Reader[T1], r2: _root_.torch.scalapy.readwrite.Reader[T2], r3: _root_.torch.scalapy.readwrite.Reader[T3], r4: _root_.torch.scalapy.readwrite.Reader[T4], r5: _root_.torch.scalapy.readwrite.Reader[T5], r6: _root_.torch.scalapy.readwrite.Reader[T6], r7: _root_.torch.scalapy.readwrite.Reader[T7], r8: _root_.torch.scalapy.readwrite.Reader[T8], r9: _root_.torch.scalapy.readwrite.Reader[T9], r10: _root_.torch.scalapy.readwrite.Reader[T10], r11: _root_.torch.scalapy.readwrite.Reader[T11], r12: _root_.torch.scalapy.readwrite.Reader[T12], r13: _root_.torch.scalapy.readwrite.Reader[T13], r14: _root_.torch.scalapy.readwrite.Reader[T14], r15: _root_.torch.scalapy.readwrite.Reader[T15], r16: _root_.torch.scalapy.readwrite.Reader[T16]): _root_.torch.scalapy.readwrite.Reader[(T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, T11, T12, T13, T14, T15, T16)] = ???

  implicit def tuple17Reader[T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, T11, T12, T13, T14, T15, T16, T17](implicit r1: _root_.torch.scalapy.readwrite.Reader[T1], r2: _root_.torch.scalapy.readwrite.Reader[T2], r3: _root_.torch.scalapy.readwrite.Reader[T3], r4: _root_.torch.scalapy.readwrite.Reader[T4], r5: _root_.torch.scalapy.readwrite.Reader[T5], r6: _root_.torch.scalapy.readwrite.Reader[T6], r7: _root_.torch.scalapy.readwrite.Reader[T7], r8: _root_.torch.scalapy.readwrite.Reader[T8], r9: _root_.torch.scalapy.readwrite.Reader[T9], r10: _root_.torch.scalapy.readwrite.Reader[T10], r11: _root_.torch.scalapy.readwrite.Reader[T11], r12: _root_.torch.scalapy.readwrite.Reader[T12], r13: _root_.torch.scalapy.readwrite.Reader[T13], r14: _root_.torch.scalapy.readwrite.Reader[T14], r15: _root_.torch.scalapy.readwrite.Reader[T15], r16: _root_.torch.scalapy.readwrite.Reader[T16], r17: _root_.torch.scalapy.readwrite.Reader[T17]): _root_.torch.scalapy.readwrite.Reader[(T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, T11, T12, T13, T14, T15, T16, T17)] = ???

  implicit def tuple18Reader[T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, T11, T12, T13, T14, T15, T16, T17, T18](implicit r1: _root_.torch.scalapy.readwrite.Reader[T1], r2: _root_.torch.scalapy.readwrite.Reader[T2], r3: _root_.torch.scalapy.readwrite.Reader[T3], r4: _root_.torch.scalapy.readwrite.Reader[T4], r5: _root_.torch.scalapy.readwrite.Reader[T5], r6: _root_.torch.scalapy.readwrite.Reader[T6], r7: _root_.torch.scalapy.readwrite.Reader[T7], r8: _root_.torch.scalapy.readwrite.Reader[T8], r9: _root_.torch.scalapy.readwrite.Reader[T9], r10: _root_.torch.scalapy.readwrite.Reader[T10], r11: _root_.torch.scalapy.readwrite.Reader[T11], r12: _root_.torch.scalapy.readwrite.Reader[T12], r13: _root_.torch.scalapy.readwrite.Reader[T13], r14: _root_.torch.scalapy.readwrite.Reader[T14], r15: _root_.torch.scalapy.readwrite.Reader[T15], r16: _root_.torch.scalapy.readwrite.Reader[T16], r17: _root_.torch.scalapy.readwrite.Reader[T17], r18: _root_.torch.scalapy.readwrite.Reader[T18]): _root_.torch.scalapy.readwrite.Reader[(T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, T11, T12, T13, T14, T15, T16, T17, T18)] = ???

  implicit def tuple19Reader[T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, T11, T12, T13, T14, T15, T16, T17, T18, T19](implicit r1: _root_.torch.scalapy.readwrite.Reader[T1], r2: _root_.torch.scalapy.readwrite.Reader[T2], r3: _root_.torch.scalapy.readwrite.Reader[T3], r4: _root_.torch.scalapy.readwrite.Reader[T4], r5: _root_.torch.scalapy.readwrite.Reader[T5], r6: _root_.torch.scalapy.readwrite.Reader[T6], r7: _root_.torch.scalapy.readwrite.Reader[T7], r8: _root_.torch.scalapy.readwrite.Reader[T8], r9: _root_.torch.scalapy.readwrite.Reader[T9], r10: _root_.torch.scalapy.readwrite.Reader[T10], r11: _root_.torch.scalapy.readwrite.Reader[T11], r12: _root_.torch.scalapy.readwrite.Reader[T12], r13: _root_.torch.scalapy.readwrite.Reader[T13], r14: _root_.torch.scalapy.readwrite.Reader[T14], r15: _root_.torch.scalapy.readwrite.Reader[T15], r16: _root_.torch.scalapy.readwrite.Reader[T16], r17: _root_.torch.scalapy.readwrite.Reader[T17], r18: _root_.torch.scalapy.readwrite.Reader[T18], r19: _root_.torch.scalapy.readwrite.Reader[T19]): _root_.torch.scalapy.readwrite.Reader[(T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, T11, T12, T13, T14, T15, T16, T17, T18, T19)] = ???

  implicit def tuple20Reader[T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, T11, T12, T13, T14, T15, T16, T17, T18, T19, T20](implicit r1: _root_.torch.scalapy.readwrite.Reader[T1], r2: _root_.torch.scalapy.readwrite.Reader[T2], r3: _root_.torch.scalapy.readwrite.Reader[T3], r4: _root_.torch.scalapy.readwrite.Reader[T4], r5: _root_.torch.scalapy.readwrite.Reader[T5], r6: _root_.torch.scalapy.readwrite.Reader[T6], r7: _root_.torch.scalapy.readwrite.Reader[T7], r8: _root_.torch.scalapy.readwrite.Reader[T8], r9: _root_.torch.scalapy.readwrite.Reader[T9], r10: _root_.torch.scalapy.readwrite.Reader[T10], r11: _root_.torch.scalapy.readwrite.Reader[T11], r12: _root_.torch.scalapy.readwrite.Reader[T12], r13: _root_.torch.scalapy.readwrite.Reader[T13], r14: _root_.torch.scalapy.readwrite.Reader[T14], r15: _root_.torch.scalapy.readwrite.Reader[T15], r16: _root_.torch.scalapy.readwrite.Reader[T16], r17: _root_.torch.scalapy.readwrite.Reader[T17], r18: _root_.torch.scalapy.readwrite.Reader[T18], r19: _root_.torch.scalapy.readwrite.Reader[T19], r20: _root_.torch.scalapy.readwrite.Reader[T20]): _root_.torch.scalapy.readwrite.Reader[(T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, T11, T12, T13, T14, T15, T16, T17, T18, T19, T20)] = ???

  implicit def tuple21Reader[T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, T11, T12, T13, T14, T15, T16, T17, T18, T19, T20, T21](implicit r1: _root_.torch.scalapy.readwrite.Reader[T1], r2: _root_.torch.scalapy.readwrite.Reader[T2], r3: _root_.torch.scalapy.readwrite.Reader[T3], r4: _root_.torch.scalapy.readwrite.Reader[T4], r5: _root_.torch.scalapy.readwrite.Reader[T5], r6: _root_.torch.scalapy.readwrite.Reader[T6], r7: _root_.torch.scalapy.readwrite.Reader[T7], r8: _root_.torch.scalapy.readwrite.Reader[T8], r9: _root_.torch.scalapy.readwrite.Reader[T9], r10: _root_.torch.scalapy.readwrite.Reader[T10], r11: _root_.torch.scalapy.readwrite.Reader[T11], r12: _root_.torch.scalapy.readwrite.Reader[T12], r13: _root_.torch.scalapy.readwrite.Reader[T13], r14: _root_.torch.scalapy.readwrite.Reader[T14], r15: _root_.torch.scalapy.readwrite.Reader[T15], r16: _root_.torch.scalapy.readwrite.Reader[T16], r17: _root_.torch.scalapy.readwrite.Reader[T17], r18: _root_.torch.scalapy.readwrite.Reader[T18], r19: _root_.torch.scalapy.readwrite.Reader[T19], r20: _root_.torch.scalapy.readwrite.Reader[T20], r21: _root_.torch.scalapy.readwrite.Reader[T21]): _root_.torch.scalapy.readwrite.Reader[(T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, T11, T12, T13, T14, T15, T16, T17, T18, T19, T20, T21)] = ???

  implicit def tuple22Reader[T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, T11, T12, T13, T14, T15, T16, T17, T18, T19, T20, T21, T22](implicit r1: _root_.torch.scalapy.readwrite.Reader[T1], r2: _root_.torch.scalapy.readwrite.Reader[T2], r3: _root_.torch.scalapy.readwrite.Reader[T3], r4: _root_.torch.scalapy.readwrite.Reader[T4], r5: _root_.torch.scalapy.readwrite.Reader[T5], r6: _root_.torch.scalapy.readwrite.Reader[T6], r7: _root_.torch.scalapy.readwrite.Reader[T7], r8: _root_.torch.scalapy.readwrite.Reader[T8], r9: _root_.torch.scalapy.readwrite.Reader[T9], r10: _root_.torch.scalapy.readwrite.Reader[T10], r11: _root_.torch.scalapy.readwrite.Reader[T11], r12: _root_.torch.scalapy.readwrite.Reader[T12], r13: _root_.torch.scalapy.readwrite.Reader[T13], r14: _root_.torch.scalapy.readwrite.Reader[T14], r15: _root_.torch.scalapy.readwrite.Reader[T15], r16: _root_.torch.scalapy.readwrite.Reader[T16], r17: _root_.torch.scalapy.readwrite.Reader[T17], r18: _root_.torch.scalapy.readwrite.Reader[T18], r19: _root_.torch.scalapy.readwrite.Reader[T19], r20: _root_.torch.scalapy.readwrite.Reader[T20], r21: _root_.torch.scalapy.readwrite.Reader[T21], r22: _root_.torch.scalapy.readwrite.Reader[T22]): _root_.torch.scalapy.readwrite.Reader[(T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, T11, T12, T13, T14, T15, T16, T17, T18, T19, T20, T21, T22)] = ???
}